name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Minimal permissions - read repo and write to PR branches only
permissions:
  contents: write # Needed for pushing to PR branches
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check format
        id: format-check
        run: |
          npm run format:check
          echo "format_needed=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Auto-fix formatting (PR only)
        if: github.event_name == 'pull_request' && steps.format-check.outputs.format_needed != '0'
        run: |
          npm run format
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No formatting changes needed after all"
          else
            git commit -m "Auto-fix formatting [skip ci]"
            git push origin HEAD:${{ github.head_ref }}
          fi

      - name: Fail on format issues (main branch)
        if: github.ref == 'refs/heads/main' && steps.format-check.outputs.format_needed != '0'
        run: |
          echo "❌ Code formatting issues detected on main branch"
          echo "Please run 'npm run format' locally and commit the changes"
          exit 1

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
