name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use a token that can push back to the repository for format fixes
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Check code formatting
        id: format-check
        run: |
          # Run format and capture if any files were changed
          npm run format

          # Check if any files were modified
          if git diff --quiet; then
            echo "formatting_needed=false" >> $GITHUB_OUTPUT
            echo "✅ All files are properly formatted"
          else
            echo "formatting_needed=true" >> $GITHUB_OUTPUT
            echo "❌ Files need formatting"
            echo "The following files were reformatted:"
            git diff --name-only
          fi

      - name: Configure Git for auto-fix
        if: steps.format-check.outputs.formatting_needed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Auto-Format"

      - name: Commit formatting fixes (PR only)
        if: steps.format-check.outputs.formatting_needed == 'true' && github.event_name == 'pull_request'
        run: |
          git add .
          git commit -m "style: auto-fix code formatting [skip ci]"
          git push origin HEAD:${{ github.head_ref }}
          echo "✅ Formatting fixes committed to PR branch: ${{ github.head_ref }}"

      - name: Fail CI due to formatting issues
        if: steps.format-check.outputs.formatting_needed == 'true'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "::error::Code formatting issues were found and automatically fixed."
            echo "::error::The formatting fixes have been committed to the PR branch."
            echo "::error::Please review the formatting changes and re-run CI."
          else
            echo "::error::Code formatting issues were found in main branch."
            echo "::error::Please run 'npm run format' locally and commit the changes."
            echo "::error::Auto-fix is only available for Pull Requests."
          fi
          exit 1

      - name: Run tests
        # Only run tests if formatting was OK
        if: steps.format-check.outputs.formatting_needed == 'false'
        run: npm test
