name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: "Dry run (no actual publish)"
        required: false
        default: false
        type: boolean

# Enhanced permissions for manual version bumping and publishing
permissions:
  contents: write # For creating commits, tags, and releases
  id-token: write # For NPM provenance

jobs:
  manual-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: version
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "🔍 DRY RUN MODE - No changes will be made"
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "new_version=dry-run-$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            NEW_VERSION=$(npm version ${{ inputs.version_type }} --no-git-tag-version)
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "✅ Version bumped to: $NEW_VERSION"
          fi

      - name: Update package-lock.json
        if: inputs.dry_run == false
        run: npm install --package-lock-only

      - name: Commit version bump
        if: inputs.dry_run == false
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
          git tag "${{ steps.version.outputs.new_version }}"

      - name: Push changes
        if: inputs.dry_run == false
        run: |
          git push origin main
          git push origin "${{ steps.version.outputs.new_version }}"

      - name: Publish to NPM
        if: inputs.dry_run == false
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: inputs.dry_run == false
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          body: |
            ## Changes in ${{ steps.version.outputs.new_version }}

            Manual release for version ${{ steps.version.outputs.new_version }}.

            Version bump type: **${{ inputs.version_type }}**
          draft: false
          prerelease: false

      - name: Summary
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "🔍 **DRY RUN COMPLETED**"
            echo "- Current version: ${{ steps.version.outputs.current_version }}"
            echo "- Would bump to: ${{ inputs.version_type }}"
            echo "- No changes were made"
          else
            echo "✅ **PUBLISH COMPLETED**"
            echo "- New version: ${{ steps.version.outputs.new_version }}"
            echo "- Published to NPM: https://www.npmjs.com/package/$(node -p 'require(\"./package.json\").name')"
            echo "- GitHub release created"
          fi
